# Copyright © 2024 ANSYS, Inc. Unauthorized use, distribution, or duplication is prohibited.
"""Autogenerated Python gRPC interface package for ansys-api-modelcenter."""

import pathlib

__all__ = ["__version__"]

with open(pathlib.Path(__file__).parent / "VERSION", encoding="utf-8") as f:
    __version__ = f.read().strip()
