# Lint directives.  Documentation:
# https://github.com/yoheimuta/protolint/blob/master/_example/config/.protolint.yaml
lint:
  # Linter directories to walk.
  directories:
    exclude:
      - codegen
      - doc
      - tests

  rules:
    # Use default rules
    all_default: true

    # - Proto files are not fully documented.
    remove:
      - FIELDS_HAVE_COMMENT
      - SERVICES_HAVE_COMMENT
      - ENUM_FIELD_NAMES_PREFIX

  # Linter rules option.
  rules_option:
    max_line_length:
      max_chars: 120